# Generated by Django 3.2.8 on 2023-02-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email_address',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
