# Generated by Django 3.2.8 on 2023-02-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_date_created', models.DateField(auto_created=True)),
                ('project_name', models.CharField(max_length=64, unique=True)),
                ('project_link', models.PositiveIntegerField()),
                ('project_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_daytime_created', models.DateTimeField(auto_created=True)),
                ('note_text', models.CharField(max_length=256)),
                ('note_active', models.BooleanField(default=False)),
            ],
        ),
    ]
