# Generated by Django 3.2.8 on 2023-02-25 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='note_id',
        ),
    ]
