# Generated by Django 3.2.8 on 2023-02-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0003_alter_todo_note_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_link',
        ),
    ]
