# Generated by Django 3.2.18 on 2023-09-22 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64, unique=True)),
                ('project_date_created', models.DateField(auto_now=True)),
                ('project_url', models.URLField(blank=True)),
                ('project_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.CharField(max_length=256)),
                ('note_daytime_created', models.DateTimeField(auto_now=True)),
                ('note_active', models.BooleanField(default=True)),
                ('note_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('note_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TODO.project')),
            ],
        ),
    ]
